My-Solar-Garden/rails_backend

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- config/routes.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users_request_spec.rb
Created CRUD endpoints for users. Also tested sad-path. Defaulted to return 204 No Content rather than return errors. Verified with Postman.
> CRUD Endpoints - User

- app/controllers/api/v1/gardens_controller.rb
- app/serializers/garden_serializer.rb
- config/routes.rb
- spec/factories/gardens.rb
- spec/requests/api/v1/garden_request_spec.rb
- spec/requests/garden_request_spec.rb
Create CRUD endpoints for gardens. For sad-path testing I followed Hash's lead for the CRUD user endpoints and return a 204 No Content.
> Crud endpoints garden

- .travis.yml
Updated travis.yml config to cache bundle to speed up builds and to block email notifications
> Add cache for bundle to speed up builds and block emails

- app/controllers/api/v1/garden_healths_controller.rb
- app/models/garden_health.rb
- app/serializers/garden_health_serializer.rb
- config/routes.rb
- spec/factories/garden_healths.rb
- spec/factories/gardens.rb
- spec/factories/sensors.rb
- spec/models/garden_health_spec.rb
- spec/requests/api/v1/garden_healths_spec.rb
closes #32 
- Created CRUD endpoints for GardenHealth. Accounted for sad paths. 
- Added validations to GardenHealth model.
> Garden health endpoints

- app/controllers/api/v1/plants_controller.rb
- app/models/plant.rb
- app/serializers/plant_serializer.rb
- config/routes.rb
- spec/factories/plants.rb
- spec/requests/api/v1/plant_request_spec.rb
Create CRUD endpoints for plants. For sad-path testing I followed Hash's lead for the CRUD user endpoints and return a 204 No Content.
> Crud endpoints plants

- app/controllers/api/v1/gardens_controller.rb
- app/models/garden.rb
- app/services/plant_service.rb
- db/migrate/20201030025324_add_private_to_gardens.rb
- db/schema.rb
- spec/factories/gardens.rb
- spec/models/garden_health_spec.rb
- spec/models/garden_spec.rb
- spec/models/sensor_spec.rb
- spec/models/user_garden_spec.rb
- spec/requests/api/v1/garden_request_spec.rb
- spec/services/plant_service_spec.rb
Adds boolean column to Gardens table for a user to determine if they want their garden to be private or public.
Adds service folder, PlantService file, test. Not robust but something to build upon.
#43 in progress
#37 done
> Plant service

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- db/migrate/20201030204952_add_uid_to_user.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_garden_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users_request_spec.rb
Added a uid column to the user table.
Added validations in the user model and user_spec.
Updated the user controller, user_params now includes uid.
Updated user factory for it to include uid. 
Updated any test that was failing because of the change in the user validations.
> Add uid to user table

- app/controllers/api/v1/gardens_controller.rb
- spec/requests/api/v1/garden_request_spec.rb
closes #62 
**Bug**:
- Create new garden wasn't actually creating a new garden or user_garden object. 
- Test was previously passing because new garden was shoveled into user's gardens within the test. 
**Resolution**:
- Resolved by using 'create' within controller. 
- Added assertion that user_garden is also created.
> Create new garden

- db/migrate/20201030204952_add_uid_to_user.rb
- db/schema.rb
Short and sweet PR. Added index for uid on the users table
> Add indexes to uid

- app/controllers/api/v1/gardens/plants_controller.rb
- app/controllers/api/v1/plants/search_controller.rb
- app/facades/plant_facade.rb
- app/models/garden.rb
- app/poros/plant_poro.rb
- app/serializers/plant_poro_serializer.rb
- app/services/plant_service.rb
- config/routes.rb
- spec/facades/plant_facade_spec.rb
- spec/models/garden_spec.rb
- spec/poros/plant_poro_spec.rb
- spec/requests/api/v1/plants/search_request_spec.rb
- spec/requests/gardens/plant_request_spec.rb
- spec/services/plant_service_spec.rb
#66 completed
If the plant already exists in the db, plant is easily added.
If the plant does not exist in the db, it is created and added to the garden.
Comments on code below.
This built upon what I did with the previous pull request [here](https://github.com/My-Solar-Garden/rails_backend/pull/65) so if you merge this before that, please feel free to just close that one.
> Add plant to garden

- app/controllers/api/v1/plants/search_controller.rb
- app/facades/plant_facade.rb
- app/poros/plant_poro.rb
- app/serializers/plant_poro_serializer.rb
- app/services/plant_service.rb
- config/routes.rb
- spec/facades/plant_facade_spec.rb
- spec/poros/plant_poro_spec.rb
- spec/requests/api/v1/plants/search_request_spec.rb
- spec/services/plant_service_spec.rb
Adds plant search functionality to the backend through the microservice, facades, service, poro. All of the above fully tested,
> Plant search

- app/controllers/api/v1/users_controller.rb
Changed code in user_params method to allow update functionality for user email.
> Update user_params in user controller

- app/controllers/api/v1/gardens/sensors_controller.rb
- config/routes.rb
- spec/requests/api/v1/garden_request_spec.rb
> Garden sensors relationship endpoint

- app/controllers/api/v1/gardens/plants_controller.rb
- app/models/garden.rb
- spec/models/garden_spec.rb
- spec/requests/gardens/plant_request_spec.rb
Reverts My-Solar-Garden/rails_backend#70
> Revert "Edits plant creation so that plants get same id in our database that …"

- app/models/garden.rb
- spec/requests/api/v1/garden_request_spec.rb
> Update models relationships, dependent destroy.

- app/models/plant.rb
- app/models/sensor.rb
- app/models/user.rb
- spec/requests/api/v1/plant_request_spec.rb
- spec/requests/api/v1/sensor_spec.rb
- spec/requests/api/v1/users_request_spec.rb
Previous PR not created correctly. Correct code updated in the PR.
> All models destroy action updated to account for relationships.

- app/controllers/api/v1/gardens/plants_controller.rb
- app/models/garden.rb
- spec/models/garden_spec.rb
- spec/requests/api/v1/gardens/plant_request_spec.rb
Reverts My-Solar-Garden/rails_backend#76
> Revert "Revert "Edits plant creation so that plants get same id in our database that …""

- app/controllers/api/v1/sensors/garden_healths_controller.rb
- config/routes.rb
- spec/requests/api/v1/sensor_spec.rb
**Changes**
- Added a sensors/garden_healths controller to handle the relationship endpoints between garden_health readings and sensors
- Added endpoint to get all readings related to a sensor
- Added endpoint to get the last reading from a sensor
> Garden health sensor relationship

- app/models/plant.rb
- spec/models/plant_spec.rb
fixes #87 
Removes all validations except for name and description. This allows plants coming in with some missing fields from the plant-microservice to be added to the database.
> 87 fix plant creation bug

- spec/requests/api/v1/users_request_spec.rb
user_params in user controller was missing one line of code during testing. Added test for full coverage. All tests passing with 100% code coverage.
> Add test for 100% coverage

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/api/v1/gardens_controller.rb
- app/facades/image_facade.rb
- app/serializers/garden_serializer.rb
- app/services/image_service.rb
- db/migrate/20201124215728_add_imageto_gardens.rb
- db/schema.rb
- spec/facades/image_facade_spec.rb
- spec/requests/api/v1/garden_request_spec.rb
- spec/services/image_service_spec.rb
Added an Image Facade and Service to get custom images for gardens
**Changes Made**
- Added an image column to the gardens table in the schema that holds a String for the image url
- Added image as an attribute to be returned by the image serializer
**Notes**
- Used Pexels API to get images
- Made the image query based on the garden name
- Made image "selection" random from the results of that query. This may return some interesting results. If anyone has ideas on how to improve the selection let me know!
closes #96
> Garden images

- .gitignore
- app/controllers/api/v1/gardens_controller.rb
- spec/requests/api/v1/garden_request_spec.rb
Updated the Garden Create action to set the default image to the stock photo if the pexel API returns nil
> Set default image on BE
